apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubernetes-node-server-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-node-server-replicaset
  template:
    metadata:
      labels:
        app: kubernetes-node-server-replicaset
    spec:
      containers:
        - name: kubernetes-node-server-replicaset
          image: kubernetes/node-web-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
