apiVersion: v1
kind: Service
metadata:
  name: kubernetes-node-server-replicaset-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30036
      port: 9090
      targetPort: 8081
  selector:
    app: kubernetes-node-server-replicaset
